### ISSUE TITLE
Dependency Error

### ISSUE THREAD

**Issue by taynotfound** [Fz77z/pterodactyl-automated-backups#2]
Traceback (most recent call last):
  File "/home/tay/pterodactyl-automated-backups/backup.py", line 5, in <module>
    from api_request import main as make_request
  File "/home/tay/pterodactyl-automated-backups/api_request.py", line 7, in <module>
    from dotenv import load_dotenv
ModuleNotFoundError: No module named 'dotenv'

Installed everything etc

**Comment by Fz77z** [comment]
hi which operating system are you running?

**Comment by taynotfound** [comment]
Ubuntu 20.04 Server

**Comment by Fz77z** [comment]
odd, that module should be installed if you followed the documentation: https://github.com/Fz77z/pterodactyl-automated-backups#installing-modules 


Can you try installing it again as per the docs and see if the issues persists?

**Comment by taynotfound** [comment]
Did it exactly as stated

**Comment by Fz77z** [comment]
Okay but python cannot find the "dotenv" module, so you'll need to double check that its installed or install it again with 
`pip install python-dotenv`

Once you can confirm the module is in-fact installed try running the script again and it should work!
